### ISSUE TITLE
Choose implementation for WETH predeploy on L2

### ISSUE THREAD

**Issue by maurelian** [ethereum-optimism/contracts#214]
Optimistic Ethereum's L2 does not have a native token like Ethereum's Ether. Rather we have an WETH-like [OMV_ETH](https://github.com/ethereum-optimism/contracts-v2/blob/master/contracts/optimistic-ethereum/OVM/precompiles/OVM_ETH.sol. ) contract pre-deployed in the genesis state: 

We need to finalize on the implementation we'll build on prior to our public mainnet launch. 

Any ETH deposited to L2 will be held in this contract.

## Wanted: 

- Secure and battle tested
- Supports [EIP-2612](https://eips.ethereum.org/EIPS/eip-2612) (ie. using `permit()` to set approvals via signature)
- Permissive licensing

## Questions: 

- Should we use WETH10 (with effectively unlimited flashminting?)

## Candidate Implementations: 

- [UniswapV2ERC20.sol](https://github.com/Uniswap/uniswap-v2-core/blob/master/contracts/UniswapV2ERC20.sol)
- [Dai](https://github.com/makerdao/dss/blob/master/src/dai.sol) (requires modifying `permit` slightly to match spec)

**Comment by TransmissionsDev** [comment]
a) Yes flashminting, allows arbing assets that become depegged fast which is important when liquidity is low in the early days.

b) Can we evaluate using an ERC777 WETH? It's got a standard for receiving contracts that's formalized (unlike WETH10)

**Comment by dmihal** [comment]
To bring the twitter discussion over here: me and @TransmissionsDev have been discussing trying to encourage more usage of ERC777 on Optimism. I've already started work on PR to make the Optimism WETH contract support ERC777.

ERC777 has a number of benefits over ERC20, including:

* Being backwards compatible with ERC20, so existing applications & apps don't need to update
* Allows apps to use "receive hooks", removing the need for users to "approve" every application. This has a number of benefits:
  - Better UX. Users aren't prompted with confusing "approve" transactions
  - Better security. Users aren't approving access to infinite funds, meaning a contract with an exploit could potentially drain all funds
  - Cheaper transfers, since allowances don't need to be updated. Admittedly, not as much of an issue on L2, but still always good to write efficient code

The biggest drawback of ERC777 is that transfer hooks open up the potential for re-entrancy attacks, such as the attack on LendFme.

However, transferring ETH has the same issue (see DAO hack), and mitigating re-entrancy is a well understood security pattern at this point.

The move to L2 is a once-in-a-lifetime to start with a blank slate, fixing some of the UX problems on L1. I'd really encourage the Optimism team & community to consider support for this. 🙂🎰

**Comment by prestwich** [comment]
Worth noting that EIP-2612 (while great) is not a replacement for ERC-777 functionality. EIP-2612 does not solve problems for contract-to-contract calls. Given the complexity growth of DeFi apps, it's reasonable to expect that contract-to-contract interactions will eventually outnumber EOA-to-contract interactions

**Comment by carlfarterson** [comment]
Is 1820 supported?

**Comment by dmihal** [comment]
@carlfarterson I've created a PR (#212) to add 1820 as a precompile.

Regardless of whether WETH is 777 or not, that PR is important to ensuring that at least other projects can use 777.

**Comment by cwhinfrey** [comment]
I think flashminting is pretty reasonable as long as there's a cap set to make it hard to overflow a value with. With the cap in place, it seems like any vulnerability that could be exploited by flash minting, could also be exploited using flash loans or by a rich attacker. The potential benefits around capital efficiency and access to liquidity for users and dapps on Optimism are worth it IMHO.

I'm a fan of ERC777 in general but worry about its security implications more than flashminting. On top of reentrancy, there are DoS attacks where recipients revert the transaction preventing some upstream or downstream action. I do see the benefits though and the security issues are easy to avoid if developers are conscious of them. Dapps that aren't built for ERC777 will very likely have issues though.

**Comment by carlfarterson** [comment]
flash minting = arbitrage
arbitrage = more efficient markets

**Comment by dmihal** [comment]
@cwhinfrey AFAIK the "DoS" issue you described would only come from an app that _needs_ to successfully transfer a token to an arbitrary address to succeed.

Given that most apps use a pull/withdraw pattern instead of push/send, seems like this issue would be somewhat rare. Do you know of any major apps that would be vulnerable to this?

**Comment by kobuta23** [comment]
IMO, ERC777 should be the baseline of all tokens on L2. 
RUs are a chance to reimagine things. Let's not get stuck with ERC20's abysmal UX forever.
Unlimited approve hell all over again.

Reentrancy concerns seem overblown. As they are a known issues anyhow, they can be addressed by SC devs

**Comment by banteg** [comment]
Keep scope as tight as you can.
WETH10 is bloated with features of questionable value. Use WETH9.
If you need permit, add permit to WETH9 and use that.

**Comment by TransmissionsDev** [comment]
Yeah I've had a change of heart about making OETH ERC777, too many contracts likely aren't prepared for possible WETH reentrancy. Especially if devs are porting their contracts designed to support default ETH and are hastily moving to WETH they might forget about the possible re-entrancy vector there.

**Comment by TransmissionsDev** [comment]
I think WETH10 is a good option as it will not break existing contracts that depend on the OG WETH.

**Comment by maurelian** [comment]
Thank you everyone for chiming in here, we really appreciate it. 🙏  Still weighing the considerations, will keep you posted.

**Comment by cwhinfrey** [comment]
> @cwhinfrey AFAIK the "DoS" issue you described would only come from an app that _needs_ to successfully transfer a token to an arbitrary address to succeed.
>
> Given that most apps use a pull/withdraw pattern instead of push/send, seems like this issue would be somewhat rare. Do you know of any major apps that would be vulnerable to this?

It came up a few times in this audit, but ERC777 was still relatively new. https://blog.openzeppelin.com/augur-core-v2-audit/

See:
```
[C05] Unfillable orders can be placed to constrain or halt markets
[C07] All dispute bonds can be held hostage or permanently frozen when a Market is in a forking universe
```

But yeah, reentrancy and this aren't the end of the world. ERC777 has nearly the same security implications as dealing with ETH directly at the end of the day.

**Comment by maurelian** [comment]
I'll just update on our thinking here: 

IMO using ERC777 is just too much of a leap from what developers expect. It's likely to break existing code, which contradicts our design goals.

To avoid surprises, we're leaning towards just using a well tested ERC20 + EIP 2612 impl without flashminting. 

We're also considering 
1) returning to be as close as possible to the EVM, without a built-in WETH
2) Having a combined ETH/WETH, as discussed [here](https://twitter.com/marek_/status/1359184003077599235)

**Comment by TransmissionsDev** [comment]
> 2\. here

Combined WETH/ETH sounds super cool. 

Can you explain why no flashminting tho? 

I think it would be very helpful to arb prices especially when liquidity is fragmented and low at the start.

**Comment by dmihal** [comment]
While my vote is still for 777, I understand the hesitance around it.

If the decision is made to not use 777, I'd strongly encourage use of WETH10, with or without flash mints. Features such as ERC677 transferAndCall can have significant improvements for cost, UX and security.
