### ISSUE TITLE
Commit the typechain contracts 

### ISSUE THREAD

**Issue by stonecoldpat** [ethereum-optimism/contracts#295]
**Is your feature request related to a problem? Please describe.**
I noticed in https://github.com/ethereum-optimism/batch-submitter they need access to OVM_CanonicalTransactionChain.sol and OVM_StateCommitmentChain.sol (example: https://github.com/ethereum-optimism/batch-submitter/blob/master/src/transaciton-chain-contract.ts#L40). It looks like they have had to do some custom work to make the functions available for the contracts.

**Describe the solution you'd like**
if the typechain of the contracts is exported from this repo, then you could easily import it to other optimism projects. So it is easy just to use the ContractFactory(). Useful for encoding function data. 

**Describe alternatives you've considered**
Seems like a nobrainer. Maybe it isn't best practice? I dunno. I am a humble typechain user. 

**Additional context**

**Comment by kfichter** [comment]
We should definitely do this. We have it in our `build` folder, but we don't put the `build/types` folder into the npm package. Unfortunately there's a bug in `hardhat-typechain` that prevents us from properly using the package because of the underscores in our contract names: https://github.com/rhlsthrm/hardhat-typechain/pull/16. We'll either have to wait for that PR to be merged or create a fork of the package.
